apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: mnist
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: magazubaev92/mnist-tfjob:v1
            command: [\"python\", \"/app/model.py\"]
            resources:
              limits:
                memory: \"8Gi\"
                cpu: \"4\"